#!/usr/bin/env bash
# configure.sh — discover this machine's layout and generate a machine-health config.
#
# Usage:
#   configure.sh            # --print: discover and show the proposed config (changes nothing)
#   configure.sh --print
#   configure.sh --apply    # write it to ~/.config/machine-health/config.sh (backs up any existing)
#
# Re-runnable any time your repos/caches change. Discovery finds your git repos, worktree
# containers, and present caches. It does NOT decide judgment calls: MH_PROTECT_REPOS is left
# EMPTY (nothing protected) and called out so you can populate it yourself.
set -u

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
# shellcheck source=lib/config.sh
. "$SCRIPT_DIR/lib/config.sh"

ACTION="print"
case "${1:-}" in
  ""|--print) ACTION="print" ;;
  --apply)    ACTION="apply" ;;
  -h|--help)  sed -n '2,12p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
  *) printf 'Unknown argument: %s\n' "$1" >&2; exit 2 ;;
esac

# Discover from the DEFAULT candidate roots (not from any existing config).
scan_roots="$(mh_existing "${MH_SCAN_ROOTS_DEFAULT[@]}")"
wt_dirs="$(
  mh_existing "${MH_WORKTREE_DIRS_DEFAULT[@]}"
  if [ -d "$HOME/.config" ]; then
    find "$HOME/.config" -mindepth 2 -maxdepth 3 -type d -name worktrees -print 2>/dev/null
  fi
)"
caches_present="$(mh_existing "${MH_CACHES_DEFAULT[@]}")"

# Re-point discovery at the existing roots, then enumerate repos.
MH_SCAN_ROOTS=()
while IFS= read -r r; do [ -n "$r" ] && MH_SCAN_ROOTS+=("$r"); done <<EOF
$scan_roots
EOF
repos="$(mh_discover_repos)"

emit_array() {  # emit_array NAME <<< "$newline_list"
  local name="$1" line
  printf '%s=(\n' "$name"
  while IFS= read -r line; do
    [ -n "$line" ] || continue
    printf '  %q\n' "$line"
  done
  printf ')\n'
}

gen_config() {
  cat <<HEADER
# machine-health config — generated by configure.sh on $(date '+%Y-%m-%d %H:%M:%S')
# Edit freely and re-run \`configure.sh --apply\` to refresh. Only existing paths are acted on.

# Where to look for git repos (worktree audit/prune, generated-output cleanup).
HEADER
  emit_array MH_SCAN_ROOTS <<EOF
$scan_roots
EOF

  cat <<'EOF'

# Containers that hold standalone worktrees (e.g. tooling-managed worktree homes).
EOF
  emit_array MH_WORKTREE_DIRS <<EOF
$wt_dirs
EOF

  cat <<'EOF'

# Explicit repos to audit/prune. Leave EMPTY to auto-discover under MH_SCAN_ROOTS.
# Discovered on this machine (uncomment to pin the list instead of auto-discovering):
EOF
  while IFS= read -r r; do [ -n "$r" ] && printf '#   %q\n' "$r"; done <<EOF
$repos
EOF
  printf 'MH_REPOS=()\n'

  cat <<'EOF'

# Extra rebuildable caches beyond the universal baseline (appended). Usually empty.
MH_EXTRA_CACHES=()

# ============================================================================
# PROTECTED REPOS — nothing is protected by default.
# Cleanup (worktree prune, generated output, node_modules) NEVER skips a repo
# unless you list it here, by basename or full path. Add entries to shield a
# critical local checkout from automated cleanup, e.g.:
#   MH_PROTECT_REPOS=( "my-critical-repo" "$HOME/Documents/some.important.repo" )
# ============================================================================
MH_PROTECT_REPOS=()
EOF
}

if [ "$ACTION" = "print" ]; then
  printf '# (--print) Proposed config for %s\n' "$MH_CONFIG_PATH"
  printf '# Caches present on this machine: %s\n#\n' "$(printf '%s' "$caches_present" | grep -c . || true)"
  gen_config
  printf '\n# Run `configure.sh --apply` to write this to %s\n' "$MH_CONFIG_PATH"
  exit 0
fi

# --apply
mkdir -p "$(dirname "$MH_CONFIG_PATH")"
if [ -f "$MH_CONFIG_PATH" ]; then
  bak="$MH_CONFIG_PATH.bak.$(date +%Y%m%d-%H%M%S)"
  cp "$MH_CONFIG_PATH" "$bak"
  printf 'Backed up existing config -> %s\n' "$bak"
fi
gen_config > "$MH_CONFIG_PATH"
printf 'Wrote %s\n' "$MH_CONFIG_PATH"
printf 'Review it, then run health_report.sh / worktree_audit.sh / clean_safe.sh --dry-run.\n'
